import time

print("|         |",end ="" flush=True)
time.sleep(1)
print("|>        |",end ="", flush=True)
time.sleep(1)
print("|=>       |",end ="", flush=True)
time.sleep(1)
print("|==>      |",end ="", flush=True)
time.sleep(1)
print("|===>     |",end ="", flush=True)
time.sleep(1)
print("|====>    |",end ="", flush=True)
time.sleep(1)
print("|=====>   |",end ="", flush=True)
time.sleep(1)
print("|======>  |",end ="", flush=True)
time.sleep(1)
print("|=======> |",end ="", flush=True)
time.sleep(1)
print("|=========|")
print("Done!")